_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
crossover_rate:
    value: 0.95
elitism_rate:
    value: 0.01
mutation_rate:
    value: 0.05
population_size:
    value: 250
