_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
crossover_rate:
    value: 1
elitism_rate:
    value: 1
elitism_type:
    value: full_elite
max_generations:
    value: 100
mutation_rate:
    value: 0
population_size:
    value: 250
